In [1]:
import pandas as pd
import os

In [29]:
csv_path = r"C:\Users\landa\Desktop\annotations.train.csv"
base_dir = r"C:\Users\landa\Desktop\train images"
output_dir = os.path.join(base_dir,"labels")
os.makedirs(output_dir , exist_ok = True)

In [4]:
df = pd.read_csv(csv_path)

In [24]:
df['class'] = df ['class'].str.strip()

In [30]:
class_names = df['class'].unique()
class_name = row ['class'].strip()
class_mapping = {"Cavity": 0 , "Fillings":1 ,"Impacted":2 , "Implant":3 }

In [31]:
for filename, group in df.groupby("filename"):
    group = group.drop_duplicates(subset = ['xmin' , 'ymin' , 'xmax' , 'ymax'])
    txt_filename = os.path.splitext(filename) [0] + ".txt"
    txt_path = os.path.join(output_dir , txt_filename)

In [32]:
with open (txt_path , "w") as f:
    for _, row in group.iterrows():
        img_w , img_h = row["width"] , row["height"]
        xmin , ymin ,xmax ,ymax = row["xmin"] , row["ymin"] , row["xmax"] , row["ymax"]
        class_id = class_mapping[row["class"]]

        x_center = ((xmin + xmax) / 2) / img_w
        y_center = ((ymin + ymax) / 2) / img_h
        box_width = ( xmax - xmin) /img_w
        box_height = ( ymax - ymin) / img_h


        f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {box_width:.6f} {box_height:.6f} \n")

In [8]:
print(sorted(df['class'].unique()))
print (class_mapping)

['Cavity', 'Fillings', 'Impacted Tooth', 'Implant']
{'Implant': 0, 'Fillings': 1, 'Impacted Tooth': 2, 'Cavity': 3}

In [23]:
print(df[df['class'].str.contains("Impacted",case=False)])

                                              filename  width  height  \
37    0412_jpg.rf.e27f70cf0b5eb7dbe5164773540f8707.jpg    512     256
38    0412_jpg.rf.e27f70cf0b5eb7dbe5164773540f8707.jpg    512     256
268   0434_jpg.rf.e97c36d720a9cba9f89e5605ed022861.jpg    512     256
272   0202_jpg.rf.e8c867b3ae2f4e0259b6faf3df7c1e85.jpg    512     256
317   0991_jpg.rf.ea947b399b3d033fec021f7f66960dee.jpg    512     256
...                                                ...    ...     ...
7943  0146_jpg.rf.de028fb54c7c5e0f614383765cbfef9c.jpg    512     256
7944  0146_jpg.rf.de028fb54c7c5e0f614383765cbfef9c.jpg    512     256
7945  0146_jpg.rf.de028fb54c7c5e0f614383765cbfef9c.jpg    512     256
8028  0283_jpg.rf.df11105141de584571ccee130f419077.jpg    512     256
8029  0283_jpg.rf.df11105141de584571ccee130f419077.jpg    512     256

               class  xmin  ymin  xmax  ymax
37    Impacted Tooth   374    68   403    99
38    Impacted Tooth   131    70   164   105
268   Impacted Tooth   352    90   382   120
272   Impacted Tooth   366   120   390   149
317   Impacted Tooth   106   139   144   176
...              ...   ...   ...   ...   ...
7943  Impacted Tooth   106   135   142   163
7944  Impacted Tooth   372    71   398   102
7945  Impacted Tooth   116    69   144   106
8028  Impacted Tooth   372   133   399   162
8029  Impacted Tooth   130    76   151   107

[428 rows x 8 columns]

In [33]:
import numpy as np

In [36]:
import matplotlib.pyplot as plt

In [37]:
data = pd.read_csv(csv_path)
data

,filename,width,height,class,xmin,ymin,xmax,ymax
0,0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg,512,256,Implant,175,116,206,153
1,0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg,512,256,Fillings,170,109,189,133
2,0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg,512,256,Implant,221,124,257,178
3,0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg,512,256,Implant,302,126,329,175
4,0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg,512,256,Implant,335,114,360,154
...,...,...,...,...,...,...,...,...
8025,0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg,512,256,Fillings,319,96,335,143
8026,0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg,512,256,Fillings,284,149,303,203
8027,0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg,512,256,Fillings,306,95,320,146
8028,0283_jpg.rf.df11105141de584571ccee130f419077.jpg,512,256,Impacted,372,133,399,162
8029,0283_jpg.rf.df11105141de584571ccee130f419077.jpg,512,256,Impacted,130,76,151,107

In [43]:
df = pd.DataFrame(data)
df
df.describe()

        width  height         xmin         ymin         xmax         ymax
count  8030.0  8030.0  8030.000000  8030.000000  8030.000000  8030.000000
mean    512.0   256.0   245.048941   105.583811   269.228767   150.546575
std       0.0     0.0    82.635357    32.019675    82.651901    32.090186
min     512.0   256.0    56.000000    24.000000    96.000000    63.000000
25%     512.0   256.0   169.000000    80.000000   193.000000   126.000000
50%     512.0   256.0   254.000000   107.000000   270.000000   150.000000
75%     512.0   256.0   320.000000   130.000000   345.000000   176.000000
max     512.0   256.0   416.000000   193.000000   456.000000   232.000000

In [40]:
df2 = pd.DataFrame(data,columns = ["class","width","height","xmin","xmax", "ymin" ,"ymax" ,"filename"])
df2
df2.describe()

        width  height         xmin         xmax         ymin         ymax
count  8030.0  8030.0  8030.000000  8030.000000  8030.000000  8030.000000
mean    512.0   256.0   245.048941   269.228767   105.583811   150.546575
std       0.0     0.0    82.635357    82.651901    32.019675    32.090186
min     512.0   256.0    56.000000    96.000000    24.000000    63.000000
25%     512.0   256.0   169.000000   193.000000    80.000000   126.000000
50%     512.0   256.0   254.000000   270.000000   107.000000   150.000000
75%     512.0   256.0   320.000000   345.000000   130.000000   176.000000
max     512.0   256.0   416.000000   456.000000   193.000000   232.000000

In [41]:
df.dropna

<bound method DataFrame.dropna of                                               filename  width  height  \
0     0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg    512     256
1     0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg    512     256
2     0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg    512     256
3     0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg    512     256
4     0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg    512     256
...                                                ...    ...     ...
8025  0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg    512     256
8026  0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg    512     256
8027  0754_jpg.rf.db2bd5c2b60f60c565a2fa1b49d81d91.jpg    512     256
8028  0283_jpg.rf.df11105141de584571ccee130f419077.jpg    512     256
8029  0283_jpg.rf.df11105141de584571ccee130f419077.jpg    512     256

         class  xmin  ymin  xmax  ymax
0      Implant   175   116   206   153
1     Fillings   170   109   189   133
2      Implant   221   124   257   178
3      Implant   302   126   329   175
4      Implant   335   114   360   154
...        ...   ...   ...   ...   ...
8025  Fillings   319    96   335   143
8026  Fillings   284   149   303   203
8027  Fillings   306    95   320   146
8028  Impacted   372   133   399   162
8029  Impacted   130    76   151   107

[8030 rows x 8 columns]>

In [46]:
print("\n Show the missing values of df : \n\n" , df.isnull().sum())

 Show the missing values of df :

 filename    0
width       0
height      0
class       0
xmin        0
ymin        0
xmax        0
ymax        0
dtype: int64

In [47]:
import pandas as pd
import os

In [73]:
csv_path = r"C:\Users\landa\Desktop\annotations.train.csv"
base_dir = r"C:\Users\landa\Desktop\train images"
output_dir = os.path.join(base_dir,"labels")
os.makedirs(output_dir , exist_ok = True)

In [80]:
image_folder = r"C:\Users\landa\Desktop\train images"
all_images = [f for f in os.listdir(image_folder) if f.endswith((".jpg" , ".jpeg" , ".png"))]
print (all_images)

['0001_jpg.rf.30a42966fb9c51553f6949b70234218d.jpg', '0001_jpg.rf.57229a11e925669019e179341e22c97a.jpg', '0001_jpg.rf.f94abcb7858bb419a7202ef60ef95bd6.jpg', '0002_jpg.rf.1a9d8354add8d9f605c343abe1f4989a.jpg', '0002_jpg.rf.2e43cdc29b00e6a96296e8e519dc4358.jpg', '0002_jpg.rf.625f03692e32d2b43b4671021ba31f80.jpg', '0006_jpg.rf.3247261244fe482ceba35bd771f399aa.jpg', '0006_jpg.rf.61c67622b420b16bf862f7b4811df532.jpg', '0010_jpg.rf.176bad8935c67e2187659bcebc3554d7.jpg', '0010_jpg.rf.61c97bc4101011d167d3b29a18d26bfc.jpg', '0011_jpg.rf.0bf9a9f6be73ff54a29df973355906c8.jpg', '0011_jpg.rf.5467f8911f832afc1e9dd3b6213b658e.jpg', '0011_jpg.rf.93ebc7324dea54f64ab06acb2a3b486e.jpg', '0012_jpg.rf.4b11c696273493e2cbf801072ae9633a.jpg', '0012_jpg.rf.72a1e0ed221d11e2ce6867b15281591c.jpg', '0012_jpg.rf.916b7a5c6895228153e732176a50a90b.jpg', '0013_jpg.rf.18d48fad3e2d024f79264bc1a060bef0.jpg', '0013_jpg.rf.2c29b82b3b4e6223787dc420b1151cf1.jpg', '0013_jpg.rf.fe31da3a7072b3d3e5d2b5ae6a8cb18b.jpg', '0015_jpg.rf.1ac936477a4dbf681db9a175c29058ff.jpg', '0015_jpg.rf.21caf812f3fa0f7b444fd67e35d905f0.jpg', '0016_jpg.rf.adae13ddc6c715828a83726187847d13.jpg', '0016_jpg.rf.e5788ea3cb728d461314e96c2e4c1b8f.jpg', '0016_jpg.rf.e993817235fb90395eef6b767122aa90.jpg', '0017_jpg.rf.1ff20e90c3f8c59d65b95fd17d734008.jpg', '0017_jpg.rf.a419702d34967acd75d9d706557b9ba8.jpg', '0017_jpg.rf.b734da38bda84b1bd73764997a4c29db.jpg', '0018_jpg.rf.56f8ed8a60455d6ff34ec81e762789a1.jpg', '0018_jpg.rf.8c3bb866b63e37391a11795af1418656.jpg', '0020_jpg.rf.4c6175050fb00bc02af74d5221801772.jpg', '0020_jpg.rf.7c945126fa01aee26f459ffcb9ba64c4.jpg', '0020_jpg.rf.8c09829d4895d807b09539c47e4bec82.jpg', '0023_jpg.rf.4ce88142dafbb4c347cb774042492a18.jpg', '0023_jpg.rf.8c727731255a3e73f3bca4115a1889c1.jpg', '0024_jpg.rf.2f510cfa6ddbba4d18f7c0241af02748.jpg', '0024_jpg.rf.a5968855a7b8c61d61917049cdfe8bbf.jpg', '0024_jpg.rf.b911ffce5a49f6b6a7965de66c4a82e6.jpg', '0025_jpg.rf.0f576055dc9afea065ac16da7cdd7456.jpg', '0025_jpg.rf.d0920a2e7484717a0575ec6381adc736.jpg', '0026_jpg.rf.27033fd1648c42a71bcf1ea3562dfdb7.jpg', '0026_jpg.rf.bbd1150741a8489f8b286191acc235a5.jpg', '0027_jpg.rf.323ec915f5634c1871647c7764ef5a60.jpg', '0027_jpg.rf.896be2bd03954080c5062ecaeed2c91f.jpg', '0027_jpg.rf.c4e40193dec7c089a48c1024c07d67ad.jpg', '0028_jpg.rf.5c8587fb90b3b6ec83ec7e4a16cf611f.jpg', '0028_jpg.rf.60f74bed91a703ce0c29984194aab034.jpg', '0028_jpg.rf.eae8628cc0a1012ad247d99ff401fb35.jpg', '0029_jpg.rf.29960599908d81b43fd268dce84a168b.jpg', '0029_jpg.rf.8a694d2007cceb4e37d3af3cfc062ac4.jpg', '0030_jpg.rf.abe64b0ff10b4d0460558b5cd350a139.jpg', '0030_jpg.rf.d6c3294e3854c3975cebbed40d8af786.jpg', '0032_jpg.rf.2b9985c7ca182c111536ab6e8a080962.jpg', '0032_jpg.rf.53511ada42c08ce437a6737a29925d22.jpg', '0032_jpg.rf.c9871fe158e2f4557f69c27ec1ed3b77.jpg', '0033_jpg.rf.3999c2ac8092e944a0d32b5716ad7162.jpg', '0033_jpg.rf.f7965451e112e0f39de9a67dbadfa766.jpg', '0033_jpg.rf.f92547f3c0afeaae38ec23ae7152de73.jpg', '0036_jpg.rf.553118cbeb44d1f8861e1a250b21e883.jpg', '0036_jpg.rf.f4139bfaa14c126ac7e7b89cc4f4e951.jpg', '0040_jpg.rf.35c228d5f93c7831c599f0b5a6389a1b.jpg', '0040_jpg.rf.81469bb3042ecfc596a8576c74035d74.jpg', '0040_jpg.rf.8fd8e24afeac4a76432ab6d6addfc73a.jpg', '0042_jpg.rf.73cc4a79fced08320315ccd42aa06a25.jpg', '0042_jpg.rf.96e7ba4a0b5dd70f037d15d80a6411d5.jpg', '0043_jpg.rf.843afa28627b222f727ca7d98ba07f98.jpg', '0043_jpg.rf.aef65631304bf5b6d9604955fb26ebb6.jpg', '0046_jpg.rf.2441983ecc53eadfd7fbbe20363a1263.jpg', '0046_jpg.rf.65f14aa9217940a4e38a99474ecf6070.jpg', '0046_jpg.rf.780f92f2364efcc0539806bbe07b8e59.jpg', '0047_jpg.rf.90a3cf6b1bd4a2120e8ec8108d0e5a5d.jpg', '0047_jpg.rf.b701489fdda45045994f30a6962d8edb.jpg', '0047_jpg.rf.c45caa1f5529abacb34ea09ec5b2e570.jpg', '0049_jpg.rf.1be8799db32cb45a578b755fef1647e8.jpg', '0049_jpg.rf.eb2342e145717c7718b3c56a2409da00.jpg', '0050_jpg.rf.4b9cd39449a68e48e5deeb7e892f79fa.jpg', '0050_jpg.rf.cbe8b8d15a7bba7c881c81e6f3930569.jpg', '0051_jpg.rf.8488c6bfe540f9a79ae7d490e2fab827.jpg', '0051_jpg.rf.d4cd7a3109e706354f4099b447e523b5.jpg', '0052_jpg.rf.5b00148f5fb6c876780ff852de6d2bce.jpg', '0052_jpg.rf.c2fd5f08f3b4c5f786c635ce13f517fd.jpg', '0054_jpg.rf.ab25b1d07817e736bc7baa6bffbaf4d7.jpg', '0054_jpg.rf.b81c1de4282e2881bc92f9d5b6ca106f.jpg', '0055_jpg.rf.b7fdd4f26ba9730b77bbe80dd7b1588c.jpg', '0057_jpg.rf.4645189826d3ad522d044d2420dcd656.jpg', '0057_jpg.rf.8baa7267fdc4580f1508670377413973.jpg', '0057_jpg.rf.8d7e6c13412563496083e15cf429bbd4.jpg', '0058_jpg.rf.0bb8e6c8dc4b829c6ad198b419120ad4.jpg', '0058_jpg.rf.792d1ba8e3ffbb5f97ae217b6ac1ad35.jpg', '0059_jpg.rf.322f640fcf5d058b67cbede8fd5664c7.jpg', '0059_jpg.rf.555ce394e75caa87090056daedb042c1.jpg', '0062_jpg.rf.375496ca44cac90e5d3fabe56683a14e.jpg', '0062_jpg.rf.5e63a5af776fd516fb0ad990624f695e.jpg', '0062_jpg.rf.a4b1465878c78c0988b5c11597193393.jpg', '0063_jpg.rf.32b4af22dcd16d98ec78e4124115178f.jpg', '0063_jpg.rf.4e65667691cc1f7946b669fe51af900c.jpg', '0063_jpg.rf.aeb0cd86456a592f166a7a42f2775a1f.jpg', '0064_jpg.rf.1b3b26905a246b00194b0c6eb7c1baf0.jpg', '0064_jpg.rf.ec3257eaccc7d94df42fa54ea520f7c1.jpg', '0064_jpg.rf.ef282450440d81788f0889f6c006410e.jpg', '0066_jpg.rf.8e643f1322ae32f174d707ad83120b51.jpg', '0066_jpg.rf.a408903c6d356ce858f8922f1f0b67e1.jpg', '0066_jpg.rf.ef19ffd9d9e9ee6a94b1ce84598a0393.jpg', '0067_jpg.rf.39355457a2a92d9e8a94529681fb1783.jpg', '0067_jpg.rf.ef3779ff5ff375721345540bd34b0fb3.jpg', '0071_jpg.rf.a781c2346bbeb5d9628402535d68d15b.jpg', '0071_jpg.rf.d52478b471ee1e43980e24bd2e6bddaf.jpg', '0076_jpg.rf.385f74c4dd2a2db8f278b42680c0bed2.jpg', '0076_jpg.rf.c662c32f0bff9712df5fcf954ef88c50.jpg', '0076_jpg.rf.fb6ea4dcb60407f2023aaef39929f171.jpg', '0077_jpg.rf.1011e6a26f5f2e6662bb66f4a5dc6b68.jpg', '0077_jpg.rf.3bae57e9681adea149d0096b9ea07403.jpg', '0079_jpg.rf.5529108d7dcaef694c3bff21e0c4c1ac.jpg', '0079_jpg.rf.f2cbcc772817315a1c02a04d772231ce.jpg', '0083_jpg.rf.53ef5461bb01354a5743cbb903274059.jpg', '0083_jpg.rf.827872bd16ef507247e89a52f3084d1c.jpg', '0084_jpg.rf.3f6ad1b3b39627f75a20e60266ce0352.jpg', '0084_jpg.rf.b17816fe35884b27c25d085e5dd8bd8e.jpg', '0084_jpg.rf.f6576e51d0f2ea8d8491d2a37047c002.jpg', '0085_jpg.rf.04d7e7d1105fa2e05b3470e4e83d4b2a.jpg', '0085_jpg.rf.1362754ffd599cc678fb816ab28010ea.jpg', '0085_jpg.rf.866589c6df70ab4284a5c59bd7b82f97.jpg', '0088_jpg.rf.393ad657fdcbe72c064d52c946f52737.jpg', '0088_jpg.rf.3bc42301f927e6216153339fc539bfdd.jpg', '0089_jpg.rf.2aa8df624bda0b0eee98c760be072962.jpg', '0089_jpg.rf.389b95d7c830b7a468ee00981176abf5.jpg', '0090_jpg.rf.0240b82bd886b1b2f632cd6f62172f3d.jpg', '0090_jpg.rf.cdf018447798e319b78c219b30046b32.jpg', '0090_jpg.rf.f055be348e14e964e22aefebd01b3d2d.jpg', '0094_jpg.rf.3b3811e24555afefc2cf3d9224d701bd.jpg', '0094_jpg.rf.4748d41c836ddd8a4dddefd36047043a.jpg', '0099_jpg.rf.099f998de5409ec6a851a398b2c8946b.jpg', '0099_jpg.rf.934dcc4bfa7a3f2dcee0f9dbc36cb039.jpg', '0104_jpg.rf.52d4e475d256203def9da1664f30462a.jpg', '0104_jpg.rf.6ffd72a07a31a49dbca8550311f61912.jpg', '0106_jpg.rf.6350f24d8ba135b8069caa9bd9f533c9.jpg', '0106_jpg.rf.7c63d232bd1781daa8ae06f1e2511100.jpg', '0108_jpg.rf.3d4bec24b49212524aa8024597464b9c.jpg', '0108_jpg.rf.5248b07a4508559ad8bd4a367ebdef39.jpg', '0109_jpg.rf.286c14f393502a14ab2c8b7ea43d3bb2.jpg', '0109_jpg.rf.7a0aba78a2e68e0014801c431fd3fa21.jpg', '0109_jpg.rf.e51226e7ad55c35a02d5dd6a45c6cede.jpg', '0112_jpg.rf.35ae566d24308af074ef2f537ef1e796.jpg', '0112_jpg.rf.c588f411ad361fcff3429b60b6901011.jpg', '0115_jpg.rf.593ae54a3ca34c425147949ee77428a1.jpg', '0115_jpg.rf.b9ec5358afbb09c02b168fd4a0daaba5.jpg', '0116_jpg.rf.e61be7fd6db9967250b6f8284319353e.jpg', '0116_jpg.rf.e82dee136add6b10a8cfdea7a86e2c86.jpg', '0116_jpg.rf.f7ba1301c36bbc5a9f6acf750277dc31.jpg', '0117_jpg.rf.4dd5f505a492d8a001f608a1f141547e.jpg', '0118_jpg.rf.6107c3c12cc076209dd34827336fbc89.jpg', '0118_jpg.rf.cda3785ae741327e12e5adf3700d99d0.jpg', '0118_jpg.rf.e7295214c195d69f605efc5a53b025eb.jpg', '0119_jpg.rf.3ff39113deff8194de26a7e51d9d1a31.jpg', '0119_jpg.rf.53f624e8b7794f36e9154f1ebc19785a.jpg', '0120_jpg.rf.7fe3c726c403ebbc1a525332b94460b4.jpg', '0120_jpg.rf.a2613fc285ab4414eef4285dc6ce88ad.jpg', '0120_jpg.rf.ff60464b44b406588898d3f183425ad0.jpg', '0122_jpg.rf.e534f5cd79ac95b234667b3d50942f19.jpg', '0122_jpg.rf.fd25de4c89200055f2565fa79b13985f.jpg', '0125_jpg.rf.611a6542904a88732612ab2a9bbce287.jpg', '0125_jpg.rf.8585fb810e48565e1921f49d7454ac44.jpg', '0126_jpg.rf.54515c03b5062f35c6964ddac63e24e0.jpg', '0126_jpg.rf.86c9ec7203c75efed22814650e34f9ea.jpg', '0127_jpg.rf.873a19147a4c590209b7223049148158.jpg', '0127_jpg.rf.a1a7906e3b863eac81ba9fbd0606e64f.jpg', '0130_jpg.rf.0ac9e5a6e6ea1830ca49136427d40411.jpg', '0130_jpg.rf.d1c7cb4c42fd97b59aeceeebed7dec13.jpg', '0135_jpg.rf.08f0d1c5777d05556bab731613a50dc8.jpg', '0135_jpg.rf.13af46a49a1466541601112ab05edc2c.jpg', '0135_jpg.rf.8e570bb3630b3fc116a1a7cc457a3c4b.jpg', '0141_jpg.rf.bb776d8244859c2425d3d0422afbf9f0.jpg', '0141_jpg.rf.d9e0bb73d73c8747bc3c4083f776a512.jpg', '0144_jpg.rf.729757d2566b80315ced40ed976f043d.jpg', '0144_jpg.rf.cd944654cce9d06bc7f31dcec922ee29.jpg', '0145_jpg.rf.5802917bcb9509525928a776b2f5dfdd.jpg', '0145_jpg.rf.5ac75327c6afb37b942fb20a20db6955.jpg', '0145_jpg.rf.b8d4fd12040d4339f83c9d2df13b1c64.jpg', '0146_jpg.rf.2898be040eae8f8b260f2d3e271c7de9.jpg', '0146_jpg.rf.43972cf1c2a4bd79b301018960a6da14.jpg', '0146_jpg.rf.de028fb54c7c5e0f614383765cbfef9c.jpg', '0153_jpg.rf.1d12a4e9724531e63687c31b4237c541.jpg', '0153_jpg.rf.5bf36b7833cea7b771abc5f6f9edc1af.jpg', '0155_jpg.rf.1c03e10464ccc2f3a96f8156353e5321.jpg', '0155_jpg.rf.a50ee2f431452cdb93c260fe494820e7.jpg', '0157_jpg.rf.2a6356c6d92e75369870f21d889f95c7.jpg', '0157_jpg.rf.f3c6b8a6024ca9a73cb4841a0ccb6f24.jpg', '0158_jpg.rf.6ba9ac13623e5a1dd9ca15ec2dc6a4a5.jpg', '0158_jpg.rf.acfc32660c641086b7fa9a7f37d9130c.jpg', '0160_jpg.rf.3498599491f1cb69968a6b0ec5cceda4.jpg', '0160_jpg.rf.aba5a72f4bc67263d318674d3c7ca9bb.jpg', '0162_jpg.rf.c484954e0dc9a5128eea6a07c3b5a531.jpg', '0163_jpg.rf.6697c199c6927c597f0db104e9c9c8e4.jpg', '0163_jpg.rf.9da3a40d8bb82c6077def7e3dc310a0b.jpg', '0163_jpg.rf.fc6e324f529b3d1333b55cbf1a88b6ea.jpg', '0166_jpg.rf.b1095ba856cad292ada26764888ccc75.jpg', '0166_jpg.rf.bb9982d8c962418d340d30dec2df8e8a.jpg', '0166_jpg.rf.d6683d3999b822a113d995f6601d31b4.jpg', '0167_jpg.rf.3e057d58f1887cf8142150debf336cf7.jpg', '0167_jpg.rf.b56a7f5ee06bf58e0ffe96ce2b975d06.jpg', '0170_jpg.rf.1b40525e90249e5988447b915ee700d8.jpg', '0170_jpg.rf.4fd8f8e6179d4c147396b5dfa63fb65e.jpg', '0170_jpg.rf.6631c1b53387b0cb420a4dda68221a05.jpg', '0171_jpg.rf.1041a67039c6ebd9583fe5eaa9323c51.jpg', '0171_jpg.rf.850e47b4642d3671f7864cb0ec4012ae.jpg', '0171_jpg.rf.ffd2ca9b6a889b38539482fbde171906.jpg', '0175_jpg.rf.16c13d67a0a634bb587fb867c507b9fd.jpg', '0175_jpg.rf.ffccecc27b1b9163370de1c7b556910b.jpg', '0177_jpg.rf.81577245f8370744eb09b4b0e2b36da3.jpg', '0177_jpg.rf.a3c605f7ed72b0c75b16a024cd53670e.jpg', '0178_jpg.rf.310e22b866a833c734f43d8b72a76447.jpg', '0178_jpg.rf.b586f4401f91c09e46097e48f7aaeb40.jpg', '0179_jpg.rf.1a863fb7d3b66fb6efd03fb11791bc38.jpg', '0179_jpg.rf.835a717f6301d4c54282c8cf3f34d9ac.jpg', '0184_jpg.rf.351a13f062c38b997043eaa80c2693ba.jpg', '0184_jpg.rf.68df51a9f1da78d89be42617045a5513.jpg', '0185_jpg.rf.50e589c3c7538f0c4d0185a810e13726.jpg', '0185_jpg.rf.9f03f11d0b267f90131c47b6f34b3802.jpg', '0187_jpg.rf.634498fb6457d31162fa083e9e0d1ef3.jpg', '0187_jpg.rf.f9bad231507ccbb648c37a2c06094018.jpg', '0193_jpg.rf.5dbc39e2c3eeea5ed15c1f9fd050bf72.jpg', '0193_jpg.rf.d6eb953cd82ac67e51d0272827254797.jpg', '0194_jpg.rf.3fa08ba5eb780e87abe9054d5c262513.jpg', '0194_jpg.rf.8c8e80765c51b70bd10aa987c6799bba.jpg', '0195_jpg.rf.3b75d4df9abc053133dd5b53b59c99f3.jpg', '0195_jpg.rf.c09ee8f8950d8512ef73bf9052ec2a6c.jpg', '0198_jpg.rf.bc9158659749ff92ca0ee57e55bde4ac.jpg', '0198_jpg.rf.c34fdae666fa8d3e699b0e7b04e33bc5.jpg', '0199_jpg.rf.129e5ebc72167160039d7c512483cabf.jpg', '0199_jpg.rf.7cc60d4182da504a58474aea921250a5.jpg', '0199_jpg.rf.e33893e6d2d348af5fd939ccffeeab03.jpg', '0200_jpg.rf.6c8e9ce3f6fa399ec450200e05f21e7d.jpg', '0200_jpg.rf.ebbe271a26c74b0307d9e48204aff4f8.jpg', '0201_jpg.rf.069a9a65083d35cb5f86b74c7c0006dc.jpg', '0201_jpg.rf.7c307a2ed1b0b4a2ed39346a6f14187d.jpg', '0202_jpg.rf.e8c867b3ae2f4e0259b6faf3df7c1e85.jpg', '0205_jpg.rf.de80511ace50e256d50ac3d92f216728.jpg', '0205_jpg.rf.fc2360b63c64b754fbdc6d0a4811f716.jpg', '0208_jpg.rf.512e25169e90d444e003ec7da731a784.jpg', '0208_jpg.rf.a514e196743c03a506fe526fda728ff2.jpg', '0211_jpg.rf.238d81a960dc8a8d3420ff1a2a53e1fb.jpg', '0211_jpg.rf.315ce8741ca53a57b4c5b40f4a3d4045.jpg', '0211_jpg.rf.bed4a07546bcc89b5b34e70fdf6231d1.jpg', '0212_jpg.rf.2435fbc9f3117046cfd40bed8788f4ac.jpg', '0212_jpg.rf.db3f8755e47a0d0572739d0452293ce0.jpg', '0212_jpg.rf.e2db14f7f6fc439b1b051440f6d3645b.jpg', '0216_jpg.rf.383ad8db30c3550784f4224029ac85b0.jpg', '0217_jpg.rf.1b4dea748b6b7a0a7caae1ce8a93c7d0.jpg', '0217_jpg.rf.624804d1d8409739781b236d7b06449c.jpg', '0217_jpg.rf.b21d198dfc0ce564889cbf2a2912f98d.jpg', '0219_jpg.rf.a63633f5d9b7666dd62a0592d68d9d01.jpg', '0219_jpg.rf.c0c803275c7d1c3e775eba2672b26b08.jpg', '0219_jpg.rf.eab99a818ba68415273c66599ad2142c.jpg', '0221_jpg.rf.18a997dd37e8db0b9fd55d67ea631e37.jpg', '0221_jpg.rf.348696493b4a4d58150f26f09f4791ff.jpg', '0222_jpg.rf.662398d205a5f1d59efe3edb9d131f73.jpg', '0222_jpg.rf.90ac0002d89bb597788f84ec8acbec00.jpg', '0222_jpg.rf.945d197cdabf23179e06c46cf6c68bf1.jpg', '0223_jpg.rf.07f8de91ab59a9e6a97587aed7bca802.jpg', '0223_jpg.rf.6a33f3f3ec9100257c3a03f531ab1bd1.jpg', '0223_jpg.rf.928d75bcc51ceedfd4ffb657a7f0d7c0.jpg', '0226_jpg.rf.47020584758fe234df43cc5f6d57420a.jpg', '0226_jpg.rf.8c646d28e72ade4b47ff9caef4727ff7.jpg', '0227_jpg.rf.8a7063fc043c94aaca609e1be396ef6b.jpg', '0232_jpg.rf.1632ccd65c8ac4c2d95e98d433ac2726.jpg', '0232_jpg.rf.efd953a42b9eb153af3a760fd6a713f0.jpg', '0233_jpg.rf.2e2b0bb9350a6ffb65b194ecf0426df7.jpg', '0233_jpg.rf.949f671288d46044e5f608e4736fcd90.jpg', '0235_jpg.rf.0a0f3ea44675a9eb3abfe8ff16bfc8cf.jpg', '0235_jpg.rf.762cf0c77e5f4aa404f67c012a71db5f.jpg', '0236_jpg.rf.1eaa39e89ab625ef7603485ac3dfcc41.jpg', '0236_jpg.rf.6e4cf75d467faf3e23ec868f79bd4119.jpg', '0236_jpg.rf.e3a13fb53c62168eb9eb2a54babd5593.jpg', '0241_jpg.rf.59f2be40cefe84285e85e3092267cc0d.jpg', '0241_jpg.rf.8b51a0f11c48748ce0b460f27ddcd7e0.jpg', '0242_jpg.rf.8bf46debb096940d320959ed5bd73734.jpg', '0242_jpg.rf.c6d5aa8ee1ae3990d0e189766db9dc36.jpg', '0242_jpg.rf.d1a2bb76d8121be65ee2e8a97049ea34.jpg', '0251_jpg.rf.09f9ba621f769dac37433e6c76e16b43.jpg', '0251_jpg.rf.28afb37c6040640b77ed627be4d2242d.jpg', '0251_jpg.rf.fa7565de0841cd5660a82a567f67f1ea.jpg', '0252_jpg.rf.b8fddca0ff38066499c477e2b5d5e65c.jpg', '0252_jpg.rf.f92f6853e5359d8a68334d26fc5ec449.jpg', '0254_jpg.rf.0c76affa5f87bd3ceb559c0f8bccc3a0.jpg', '0254_jpg.rf.c09147555338c8640641f751805c3e79.jpg', '0254_jpg.rf.e2370b19315f494e8da966885e1f338f.jpg', '0255_jpg.rf.6cc810ba280add3ba1b78a59cf2faf41.jpg', '0256_jpg.rf.1411d256155537bcb812feea21304d6a.jpg', '0256_jpg.rf.d9c4f2e94ef26baed162c5e3e0feab03.jpg', '0257_jpg.rf.540ec8fb87629ab11a5e666e9ef525c1.jpg', '0257_jpg.rf.891576f456f1153a791e3405176f3e15.jpg', '0258_jpg.rf.1579e184e84294fd6cdff94638850d35.jpg', '0258_jpg.rf.446ae1676ce23646695f47477e3f3130.jpg', '0259_jpg.rf.199d44970b4e34a0fa60db1566793d98.jpg', '0259_jpg.rf.a1c60bb2dd29f8b360fab7a7e86da82a.jpg', '0259_jpg.rf.ed7b8f15d059987955f038b50a459cfd.jpg', '0260_jpg.rf.46478b16a817bdc57e3071f5cfc9e8c1.jpg', '0260_jpg.rf.ba361960a610ebf298cc367692da0a50.jpg', '0261_jpg.rf.3935580527a97adf70199d6525b2f232.jpg', '0261_jpg.rf.cb05c1dcdaf9b00d30a54790268ac425.jpg', '0265_jpg.rf.3c921ec02bb245892eea071236ba62c5.jpg', '0265_jpg.rf.ed76973ef2f897e8bf319706efd24170.jpg', '0266_jpg.rf.a8b17e3a8803552a4611c663cacb20c2.jpg', '0266_jpg.rf.d2cc38bf7a1457bff27c16b207909504.jpg', '0266_jpg.rf.fa548228b59b51268581cc13a490319e.jpg', '0267_jpg.rf.efdea5f052db2a839712ea373345c2aa.jpg', '0267_jpg.rf.f6a813425844e1a0811081e31d777a64.jpg', '0271_jpg.rf.5a1423f746163696ee3a3128dceb28b1.jpg', '0271_jpg.rf.c08fa4f6be3178699751775b9655c123.jpg', '0271_jpg.rf.e18d2d727c6d0c029f5b6024f39058d6.jpg', '0275_jpg.rf.632710ff6403e90b01b4fc53de3bf2ee.jpg', '0275_jpg.rf.a552f241817bf8bae12ceb4eca8d03a8.jpg', '0275_jpg.rf.cae3a6dc590e95704449f9eb1ff0870d.jpg', '0281_jpg.rf.3e9857f0562f99ba590782c5ef2cfa8b.jpg', '0281_jpg.rf.b5be34f4b31c988b838481867415e3f5.jpg', '0283_jpg.rf.df11105141de584571ccee130f419077.jpg', '0283_jpg.rf.ebba77db440fe597b007919525292a29.jpg', '0285_jpg.rf.09e7042ba4b8d0c4e2a1078a63cba976.jpg', '0285_jpg.rf.f9c22558cd2ddfe407d4d1cdf77978e0.jpg', '0287_jpg.rf.1291803cffcb43bdb6fb65569990b970.jpg', '0287_jpg.rf.34304fa9a9ae3c63fb3519acbb6af802.jpg', '0291_jpg.rf.beb0d60e74991813ed9a3434d030cce1.jpg', '0291_jpg.rf.bfc887aafd0d7c6492d25a022018f8ed.jpg', '0295_jpg.rf.61f320e813afea89307b5b96c017b640.jpg', '0295_jpg.rf.9de4953c45ed3acdff06b1afb1138f45.jpg', '0300_jpg.rf.54bc5b91b567b98224b6fab8cbb6677e.jpg', '0300_jpg.rf.79aa205f92083ebff3610e92ff8df60c.jpg', '0301_jpg.rf.8d6fe01f54892d0932bbfb7a7c80aff5.jpg', '0301_jpg.rf.c6352591bd1959de9ed6f9927356ce63.jpg', '0301_jpg.rf.df03dfd545d23f6b819da2e20d5bef58.jpg', '0303_jpg.rf.86a2c2655263e700a2dfc961c4c659ca.jpg', '0303_jpg.rf.e599e719683faedca7bb627ce43fcf80.jpg', '0303_jpg.rf.f46c570389da9111d7a0ada3689f0a06.jpg', '0304_jpg.rf.14efc61a51aa5003113f27d4c74e0d80.jpg', '0304_jpg.rf.4d4e47e46979e47028a60557236ba1cc.jpg', '0304_jpg.rf.51e742ef19f59d10815c7375c8fbdb3a.jpg', '0308_jpg.rf.39bfefbd46345a3821ecb4c7a60ec85d.jpg', '0308_jpg.rf.8ed4e3ef4af2ccafcaf99db78302f0a8.jpg', '0309_jpg.rf.e5a518937e4a91948e7e04fabb3045a0.jpg', '0309_jpg.rf.f554bd45d4a135678297ef1d90e1debd.jpg', '0310_jpg.rf.a9d65e3b22dfccd8a59e5263ee64cf50.jpg', '0310_jpg.rf.f3babf8664aae0f70d1150714f715cb9.jpg', '0310_jpg.rf.fd04b7d595664cff5b5703f11e41c1da.jpg', '0312_jpg.rf.a3b1695f851900ec415a5f75cb8283a2.jpg', '0312_jpg.rf.cf0a8649fb3e1fd113cfaf77d9d22a85.jpg', '0316_jpg.rf.86dee7b3bb838a6a2ebaf117bca6ac44.jpg', '0316_jpg.rf.ae9b196a4d8cb8ee56e315a4bca0ea38.jpg', '0316_jpg.rf.b6bdf8e1ca87a5cbba9972df2ba7f5d4.jpg', '0317_jpg.rf.a63c98787750751a759986a47d297e11.jpg', '0317_jpg.rf.d5d6cf81a402159c8941ae63a0af69cc.jpg', '0317_jpg.rf.dec4214751c408b5a1de1391f7db9af6.jpg', '0318_jpg.rf.23a8cc7801381c084173a204daa3ebe5.jpg', '0318_jpg.rf.4f38b88471ac34991ad730b83f5a28c3.jpg', '0320_jpg.rf.01af7923754c344871281322fb8e5d66.jpg', '0320_jpg.rf.44f757cb8bda6b63208f21fab5ae6a5d.jpg', '0320_jpg.rf.fb6370e77e21004881b6d8ceaf228412.jpg', '0321_jpg.rf.0fba4cc0beeb1464cb8b67bae5fa5db1.jpg', '0321_jpg.rf.24692cc266fe134af741c38ee2241482.jpg', '0321_jpg.rf.9e215071e997bf25150bf2f783c35a2c.jpg', '0324_jpg.rf.787d9c14a52f2b8352566449733740da.jpg', '0324_jpg.rf.abc4d4ecda0118d9f9b7efa365d8373d.jpg', '0325_jpg.rf.027ef1f92ff5b84b942588ab9f6a1987.jpg', '0325_jpg.rf.30d8d6d4c8432c7f330725f602069076.jpg', '0325_jpg.rf.52a5f4ee0b7c7fc41ebfeb3fcab2f55b.jpg', '0328_jpg.rf.642692efd798286d1225538be4a2a746.jpg', '0328_jpg.rf.f69c579b68e9e0c0e6990d813920820f.jpg', '0330_jpg.rf.16c89c591f50ef0b3d1dfc296e7926f9.jpg', '0330_jpg.rf.c4eca1f0b61f5e030ac0517d1d1a3f25.jpg', '0332_jpg.rf.3edc3a1d5ff75c38f768538cec7f1aab.jpg', '0332_jpg.rf.5ec30d5f41ad98e1b782f90b0e5833bb.jpg', '0333_jpg.rf.43b02c8ec229b1fab687ab65fa47ca2e.jpg', '0333_jpg.rf.8ab567a59f13099098eff3a65d3d9fb3.jpg', '0333_jpg.rf.a7dada8328229a84c76eb3e259947079.jpg', '0334_jpg.rf.922058dc8f930830a5f01621236cd308.jpg', '0334_jpg.rf.afba46dfc2e8db43b86eaefe0c9c5b06.jpg', '0334_jpg.rf.eb62c646bfaa9db3c3d803a3cec6d515.jpg', '0335_jpg.rf.048e48b19e4d3369f7eec9160f59dfd6.jpg', '0335_jpg.rf.294202e67d9dc9d18d302683c528e9d0.jpg', '0335_jpg.rf.d0359cde1de9b9c10c3daa3bc248b0dc.jpg', '0336_jpg.rf.d3078a4c9ae5285eff1e31e422458692.jpg', '0336_jpg.rf.debdd846e9c70c0422755c3ed1506eea.jpg', '0336_jpg.rf.f3614a0b62b052d727755ac2c2201fcf.jpg', '0340_jpg.rf.00d920546b456209de688af0f98e8000.jpg', '0340_jpg.rf.3088c3aec5bc8a293f9237448e3262e1.jpg', '0340_jpg.rf.ee679f8c0931d2e1ce5d613efd992aa9.jpg', '0341_jpg.rf.0ffc0cffc0aeb02dd9

In [75]:
df = pd.read_csv(csv_path)

In [76]:
df['class'] = df['class'].str.strip().str.capitalize()

annotated_images = df['filename'].unique()
annotated_images = [os.path.basename(f) for f in annotated_images]

classes= sorted(df['class'].unique())
class_map = {cls : idx for idx , cls in enumerate(classes)}
print (" class map :" ,class_map)

 class map : {'Cavity': 0, 'Fillings': 1, 'Impacted': 2, 'Implant': 3}

In [77]:
def convert_to_yolo(row,width,height,class_map):
    class_id = class_map[row['class']]
    x_center = (row['xmin'] + row['xmax']) / 2 / width
    y_center = (row ['ymin'] + row['ymax']) / 2 / height
    box_width = (row ['xmax'] - row ['xmin']) / width
    box_height = (row ['ymax'] - row ['ymin']) / height

    return f"{class_id} {x_center} {y_center} {box_width} {box_height}"

In [78]:
grouped = df.groupby('filename')
for filename , group in grouped:
    output_lines =[]
    width = group ['width'].iloc[0] 
    height = group ['height'].iloc[0]


    for _, row in group.iterrows():
        yolo_line = convert_to_yolo(row,width,height,class_map)
        output_lines.append(yolo_line)
        output_filepath = os.path.join(output_dir ,f"{filename.split('.')[0]}.txt")

In [79]:
with open(output_filepath, "w") as f:
    f.write("\n".join(output_lines))

In [55]:
print(df['class'].unique())

['Implant' 'Fillings' 'Impacted' 'Cavity']

In [60]:
filename = '0674_jpg.rf.e02a155a0c135687b9301ff9a20d220a.jpg'
df[df['filename'] == filename]['class'].value_counts()

class
Fillings    7
Implant     6
Name: count, dtype: int64